version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hola_mundo
      POSTGRES_USER: hm_user
      POSTGRES_PASSWORD: hm_pass
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
