server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hola_mundo}
    username: ${DB_USER:hm_user}
    password: ${DB_PASS:hm_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
